services:
    ui:
      command: puma --debug -w 2
      volumes:
        - ui_src:/app
    post:
      volumes:
        - post_src:/app
    comment:
      command: puma --debug -w 2
      volumes:
        - comment_src:/app

volumes:
    ui_src:
    comment_src:
    post_src:
